23 component querybar
nology-tech/verde-client-project pull request #29
Opened 2024-01-11 16:29 UTC by amancalledkidd

Created a query bar component and reusable search box components.
Added new assets into image folder.
Reponsive for desktop hidden on mobile.
Optional filter button included.

2024-01-11 20:38 UTC, mh-fung requested changes
Hiya,
Not much to add, but could you guys help to fix the following issues, most of them are simply about the styles and the positioning of the elements?
 
Update repo
Make the image in the searchBox slightly larger and more visible.
Replace px with rem
Add light/dark mode styles

Thanks

2024-01-12 10:08 UTC, Matthew-Hughes3488 commented
Added changes

2024-01-12 10:36 UTC, mh-fung approved these changes
Nice work. Thanks

2024-01-12 10:47 UTC, fihockey approved these changes

2024-01-12 10:47 UTC, merged